name : Java App Deployment

on : 
  push :
    branches: [project_01]
permissions:
    id-token: write
    contents : read

jobs:
   build:
    runs-on : ubuntu-latest

    steps: 
      - name : checkout
        uses : actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: '17'
      - name : Configure AWS Credentials using OIDC
        uses : aws-actions/configure-aws-credentials@v4
        with : 
            aws-region : us-east-1
            role-to-assume : ${{ secrets.AWS_IAM_ROLE}}
      - name : Test AWS IAM Role
        run : aws sts get-caller-identity

      - name : Build App
        run : mvn clean package
        working-directory : Java-Login-App


