name :  Terraform aws deploy 

on :
    push :
        branches :
            - project_01

permissions:
    id-token : write
    contents : read

jobs:

    terraform: 
        runs-on : ubuntu-latest

        steps:
            - name : checkout repo
              uses : actions/checkout@v4

            - name : Configure AWS  Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                 role-to-assume : arn:aws:iam::599548906743:oidc-provider/token.actions.githubusercontent.com
                 aws-region : us-east-1
        
            - name : setup Terraform
              uses : hashicorp/setup-terraform@v4
               
            - name: Terraform Init
              run: terraform init
              working-directory: terraform

            - name: Terraform Validate
              run: terraform validate
              working-directory: terraform

            - name: Terraform Plan
              run: terraform plan
              working-directory: terraform

            - name: Terraform Apply
              if: github.ref == 'refs/heads/project_01'
              run: terraform apply -auto-approve
              working-directory: terraform
    